apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::190203316789:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1J5Q1N8V04PLS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::190203316789:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-06T17:28:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1723"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6e06022a-4a59-442d-9ec2-102919fae7eb
